### ISSUE TITLE
Location of demo.json and license

### ISSUE THREAD

**Issue by travisbrady** [tapilab/aaai-2015-demographics#2]
In the readme you mention data/demo.json, but there is no such file in the data directory.
Did you forget it or does it need to be recreated?

Also, under what license have you released this code and data?

**Comment by aronwc** [comment]
Hi,

We've decided not to post demo.json; however, you can regenerate with the below:
```
$ cd src
$ python qcast.py ../data/sites.txt  > ../data/demo.json
```
`data/sites_twitter.txt` then can be used to add back the twitter accounts for each brand.

The demographic values may be slightly different, since these change over time. Contact me if your goal is to reproduce our exact numbers.

I've also updated LICENSE.txt (GPL3).

Best,
Aron
